WITH crec_tbs AS (
SELECT REPLACE(entity_name, '.acp', '') INSTANCIA,
  TO_CHAR(collection_time, 'MM/YYYY') MES,
  ROUND(NVL(max_value, 0)/1024, 2) MAXIMO
    FROM sysman.gc$metric_values_daily METRICA
      WHERE METRICA.entity_type = 'oracle_database'
        AND METRICA.entity_name IN (SELECT m.member_target_name FROM MGMT$TARGET_MEMBERS m WHERE m.aggregate_target_name IN ('DataBase Produccion')) 
        AND METRICA.metric_group_name = 'tbspAllocation'
        AND METRICA.metric_column_name = 'spaceUsed'
        AND METRICA.key_part_1 NOT LIKE '%TEMP%'
        AND METRICA.key_part_1 NOT LIKE '%UNDO%'
        AND collection_time IN (
                          (SELECT TO_DATE(TO_CHAR(SYSDATE,'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-1),'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-2),'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-3),'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-4),'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-5),'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-6),'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-7),'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-8),'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-9),'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-10),'YYYYMM') || '01', 'YYYYMMDD') FROM dual),
                          (SELECT TO_DATE(TO_CHAR(ADD_MONTHS(SYSDATE,-11),'YYYYMM') || '01', 'YYYYMMDD') FROM dual)
                          )
      ORDER BY collection_time DESC
)
SELECT x.INSTANCIA
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(SYSDATE,'MM/YYYY')) "ACTUAL"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'MM/YYYY')) "HACE 1 MES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-2),'MM/YYYY')) "HACE 2 MESES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-3),'MM/YYYY')) "HACE 3 MESES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-4),'MM/YYYY')) "HACE 4 MESES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-5),'MM/YYYY')) "HACE 5 MESES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-6),'MM/YYYY')) "HACE 6 MESES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-7),'MM/YYYY')) "HACE 7 MESES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-8),'MM/YYYY')) "HACE 8 MESES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-9),'MM/YYYY')) "HACE 9 MESES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-10),'MM/YYYY')) "HACE 10 MESES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-11),'MM/YYYY')) "HACE 11 MESES"
       ,(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(SYSDATE,'MM/YYYY'))-(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-11),'MM/YYYY')) "CRECIMIENTO ANUAL"
       ,ROUND(((SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(SYSDATE,'MM/YYYY'))-(SELECT SUM(NVL(y.MAXIMO,0)) FROM crec_tbs y WHERE y.INSTANCIA = x.INSTANCIA AND y.MES = TO_CHAR(ADD_MONTHS(SYSDATE,-11),'MM/YYYY')))/12, 2) "CRECIMIENTO MENSUAL PROMEDIO"
  FROM ( 
         SELECT DISTINCT m.INSTANCIA FROM crec_tbs m
       ) x
  ORDER BY x.INSTANCIA;
